### ISSUE TITLE
Ldo3 output voltage

### ISSUE THREAD

**Issue by clow57** [Xinyuan-LilyGO/TTGO-T-Watch#11]
I am using T-watch with Acsip S76G lora/gps chip. On all the example code LDO3 is set to 1800mv. What is the reason for this? As far as I understand S76G is a 3.3v chip. I have two T-watches I was running one on the 1800mv code from the examples, but it has now completely stopped functioning. Will no longer respond to uart commands. The other I am running on 3300mv from LDO3 it is functioning fine. Any ideas how to reset the Acsip chip. I have tried power cycling, but I cannot get a response on uart to reset the chip. If possible can you guys please post S76G datasheet. I have contacted Acsip, but they will only deal with suppliers. 

Thanks

**Comment by lewisxhe** [comment]
@clow57 Hello, LD3 is responsible for the s7xg main chip power supply, and LDO4 is responsible for providing s7xg gps reset circuit power supply, if the UART does not respond, please check if ldo3 has been turned on, and has been set to DCIN mode
[S76G Application Note_Ver.C_20190403.pdf](https://github.com/Xinyuan-LilyGO/TTGO-T-Watch/files/3567409/S76G.Application.Note_Ver.C_20190403.pdf)

**Comment by clow57** [comment]
Thanks @lewisxhe Just to confirm LDO2 should be at 3.3v and is connected to display back light  LDO3 should be at 3.3v and LDO4 at 1.8V is that correct? What controls power to ST7789V, FT5206, BMA423?

It would be really helpful to have all s7xg documentation available. For example the command reference pdf linked in one of the github repositories does not include the rf commands. I had to use s7678s command reference to find the commands. Datasheet and an updated command reference sheet would be helpful. Also schematics for main board and s76g board. I was given schematics for s76g board from sales, but I still need main pcb schematic. It would be helpful for others I am sure. 

I am calling axp.begin(Wire); then axp.setPowerOutPut(AXP202_LDO3, AXP202_ON); in setup, but when I check Serial.println(axp.isLDO3Enable()); I get 0. Checking at the test points I see no voltage on 1V8 or LDO3. I have 3.3V on DCDC3 How do I set DCIN Mode?

**Comment by lewisxhe** [comment]
You should use it like this
```
axp.setLDO3Mode(1);
axp.setPowerOutPut(AXP202_LDO3, AXP202_ON);
```

DCDC3 has no DCIN mode, DCIN mode is only for LDO3

**Comment by clow57** [comment]
Thanks again. I tried adding axp.setLDO3Mode(1); I still have no power on LDO3. How do I set LDO3 to DCIN?

**Comment by lewisxhe** [comment]
Check the test point for voltage by simple test
```
Wire.begin(21,22);
Axp.begin(Wire);
axp.setLDO3Mode(1);
axp.setPowerOutPut(AXP202_LDO3, AXP202_ON);
```
If it still doesn't work, the following connection is my integrated peripheral driver library, you can test it
https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library.git

**Comment by clow57** [comment]
That did it. I wasn't calling Wire.begin. Silly mistake. Thanks for your help. I am just finishing a program for configuring all Lora and GPS setting from a user defined config. I am also going to have it read out Axp202 settings from your library to help with debugging. 

It would still be really helpful to have the other documentation online. 

Thanks for your help.
Chris

**Comment by kimwo21** [comment]
I am also working on the  S76G.  Could you copy the schematic that you say you got from sales.  Thank you
