### ISSUE TITLE
Battery Life

### ISSUE THREAD

**Issue by SeungRyeol** [Xinyuan-LilyGO/TTGO-T-Watch#14]
How many hours can I use on a 180mAh battery when the GPS update cycle is 1 second and data is sent to the web server via esp32 every second?

**Comment by sysdl132** [comment]
May depend on how long you use. This is a very uncertain quantity.

**Comment by SeungRyeol** [comment]
Can't tell the approximate battery life under the above conditions?

**Comment by SeungRyeol** [comment]
Or is there battery life data including test conditions and results?

**Comment by sysdl132** [comment]
If you turn on the screen,it can work about 2 hours(maybe).
If you turn off the screen,it can work for a long time.
---------------------------------------------------------------------------
If you use battery like that,maybe it can use about 2 years.

**Comment by SeungRyeol** [comment]
We will proceed with using the screen off. Thank you so much for your answer.
