### ISSUE TITLE
forum issue

### ISSUE THREAD

**Issue by TonyVie** [Xinyuan-LilyGO/TTGO-T-Watch#2]
Hi !
Just FYI I cant register in the forum (http://118.89.24.206:4567)

I have an infinite spinning wheel in top bar:
![image](https://user-images.githubusercontent.com/1685349/60731684-7c193800-9f48-11e9-8f81-68f79134edc6.png)

And this message in console:
VM28:1 GET http://118.89.24.206:4567/socket.io/?EIO=3&transport=polling&t=Ml2jAQS 403 (Forbidden)

**Comment by lewisxhe** [comment]
The forum will be open in the future
